name: 获取GitHub数据

on:
  schedule:
    # 每天凌晨3点运行
    - cron: '0 3 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置Node.js环境
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: 安装依赖
        run: npm install axios
        
      - name: 获取GitHub数据
        run: node .github/scripts/fetch-github-data.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 提交更新的数据
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/
          git commit -m "更新GitHub数据 $(date +'%Y-%m-%d')" || echo "没有变更"
          git push